DROP TABLE ARTICLES IF EXISTS;
DROP SEQUENCE IF EXISTS global_seq;

----- for the hsqlbd
CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE ARTICLES
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    title            VARCHAR(255)             NOT NULL,
    news_site        VARCHAR(1000)            NOT NULL,
    published_date   DATETIME                 NOT NULL,
    article          CLOB                     NOT NULL
);
